[build]
  # Direktori output build
  publish = "dist"
  
  # Command untuk build - menggunakan script yang memastikan dependencies terinstall
  command = "npm ci --production=false && npm run build"
  
  # Direktori base (opsional, default adalah root)
  base = "."

[build.environment]
  # Versi Node.js yang kompatibel
  NODE_VERSION = "18"
  
  # Environment variables untuk production
  NODE_ENV = "production"
  
  # Menggunakan npm untuk install dependencies
  NPM_FLAGS = "--production=false"

# Konfigurasi untuk SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers untuk optimasi performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache untuk file JS dan CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Konfigurasi untuk file images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build plugins untuk optimasi
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Konfigurasi untuk preview deployments
[context.deploy-preview]
  command = "npm ci --production=false && npm run build"

[context.branch-deploy]
  command = "npm ci --production=false && npm run build"

# Development context
[context.dev]
  command = "npm ci --production=false && npm run build:dev"

# Production context
[context.production]
  command = "npm ci --production=false && npm run build"